app:
  name: "web_app"
  mode: "dev"
  port: 9091

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 11006
  user: "root"
  password: "123456"
  name: ""
  max_open_connections: 200
  max_idle_connections: 50

redis:
  host: "127.0.0.1"
  password: 123456
  port: 6379
  db: 0
  pool_size: 100
